# Generated by Django 2.2.6 on 2019-11-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20191102_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='body',
            field=models.TextField(verbose_name=''),
        ),
    ]
